backend:
  name: github
  repo: JenuTandel/Docusaurus_Aektra_Timesheet
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "timesheet docs"
    label: "Timesheet Docs"
    folder: "docs/timesheet"
    format: "frontmatter"
    identifier_field: "title"
    nested:
      depth: 10
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "performance review docs"
    label: "Performance Review Docs"
    folder: "docs/performance-review"
    format: "frontmatter"
    identifier_field: "title"
    nested:
      depth: 10
    create: true
    slug: "{{fields.parent_path | default('performance-review')}}/{{fields.title | slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
