backend:
  name: github
  repo: JenuTandel/Docusaurus_Aektra_Timesheet
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    format: "frontmatter"
    identifier_field: "title"
    nested:
      depth: 3
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
        }
      - { label: "Body", name: "body", widget: "markdown" }
